### ISSUE TITLE
在Windows下功能不正常

### ISSUE THREAD

**Issue by xiao-gy** [niuhuan/pansy#3]
windows下无法点击图片详细页面右上角的设置按钮以及主页左上角的设置按钮

**Comment by xiao-gy** [comment]
保存图片也不正常

**Comment by niuhuan** [comment]
> windows下无法点击图片详细页面右上角的设置按钮以及主页左上角的设置按钮

那个按钮暂时只是个摆设，没有添加功能，将来想加入下载整个图册的功能。

0.0.2在macos和android测试，长按图片后的菜单里可以保存原图到本地。windows一会儿我会测一下。
0.0.2

**Comment by xiao-gy** [comment]
可以用可以用，就是下载完成才会弹对话框，我以为用不了

**Comment by niuhuan** [comment]
> 可以用可以用，就是下载完成才会弹对话框，我以为用不了

这个工具还不是很成熟，如果您对漫画感兴趣，可以看看我的其他仓库。

https://github.com/niuhuan/daisy
https://github.com/niuhuan/jasmine
https://github.com/niuhuan/pikapika

之类的

**Comment by xiao-gy** [comment]
> > 可以用可以用，就是下载完成才会弹对话框，我以为用不了
> 
> 这个工具还不是很成熟，如果您对漫画感兴趣，可以看看我的其他仓库。
> 
> https://github.com/niuhuan/daisy https://github.com/niuhuan/jasmine https://github.com/niuhuan/pikapika
> 
> 之类的

okk，谢谢你
