### ISSUE TITLE
无法授权登录pansy

### ISSUE THREAD

**Issue by cicerocx** [niuhuan/pansy#4]
具体为点击登录后跳转网页进行授权，然后跳回pansy还是在登录界面

**Comment by niuhuan** [comment]
安卓 or 苹果?

**Comment by cicerocx** [comment]
机型为redmi k40 ，android12，下载版本为v0.02-android-arm64

**Comment by niuhuan** [comment]
可以尝试关闭程序然后打开试一下。如果还是不行的话, 大概是因为pansy, 没有适配Android12。请先不要关闭issue。

**Comment by NahidaBuer** [comment]
iOS也不行……总之就是登录不了。感觉没有关联pixiv的链接，装了pixiv官方客户端的话可以唤起官方客户端，然而不管安装顺序，都无法唤起pansy
![5627A350-DD23-4C0F-BACF-615975F3EA82](https://user-images.githubusercontent.com/53059854/182067135-3c016400-74b3-43da-ad51-6f7228956402.png)

**Comment by niuhuan** [comment]
可否尝试一下前两个版本?  @CHxCOOH

**Comment by zycboss** [comment]
0.0.3还是一样的问题，并没有解决
登陆完显示跳转回到app，结果还是登陆按钮

设备华为P30
鸿蒙2.0应该还是安卓11，也有可能还是安卓10

**Comment by niuhuan** [comment]
我用模拟器是登录成功了的，软件设置里面有没有默认连接选项之类的？

**Comment by niuhuan** [comment]
先使用我的其他软件吧 daisy jasmine wax pikapika. 这个我还需要很久才能搞好 哭😭

**Comment by zycboss** [comment]
用系统自带的浏览器可以完成登录，三方浏览器不行

**Comment by PGBTT** [comment]
同样是无法登录，浏览器输入完密码后转跳到软件首页后不会登录

**Comment by niuhuan** [comment]
我不知道你们什么情况，但是安卓模拟器可以

**Comment by niuhuan** [comment]
我已经佛系了，也许应该用各个版本的安卓debug一下
